### ISSUE TITLE
Error within convertHeaders.py

### ISSUE THREAD

**Issue by sagarutturkar** [IMB-Computational-Genomics-Lab/BGIvsIllumina_scRNASeq#1]
Hello,

I am trying to run this script for the one of your data file **JE1902_D0_R1.fastq.gz** downloaded from SRA.  
I renamed the file as "**JE1902_scRNA_D0_ACCCTCCT_S1_L001_R1_001.fastq.gz**".  
Next I tried to run the code:

```
python2.7 convertHeaders.py \
-i JE1902_scRNA_D0_ACCCTCCT_S1_L001_R1_001.fastq.gz \
-o JE1902C_scRNA_D0_ACCCTCCT_S1_L001_R1_001.fastq.gz
```

I get an error as:

```
Traceback (most recent call last):
  File "convertHeaders.py", line 105, in <module>
    for line in line_chunk:
NameError: name 'line_chunk' is not defined

```

I see that "line_chunk" is used only once in the script "convertHeaders.py". Can you please help to fix this.

**Comment by asenabouth** [comment]
Hi @sagarutturkar ,

Please use the code in this repository https://github.com/powellgenomicslab/BGI_vs_Illumina_Benchmark

Regards,
@asenabouth

**Comment by shenwei356** [comment]
Just need rename `line_chunk` to `input_fastq`.
